[package]
name = "new_to_rust"
version = "0.1.0"
authors = ["VivekKashyapS98 <vivekyeskashyap@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
